// Real documents crawled from community.vantiq.com/docs/ and dev.vantiq.com/docs/
// on 2026-08-14 — every id/title/href/description below traces back to an actual live
// page (129 of 130 fetched successfully for their description; the one fetch failure,
// the malformed "Create a MCP Server" forum link, ships with an empty description rather
// than an invented one). This is the same 130-document corpus and 13-topic categorization
// documented in "Vantiq Knowledge Base Tracker.xlsx" (Documents by Category / KB Tracker).
// Release Notes is excluded here — it has its own dedicated entry point on this page.
// "Get Started" (Quickstart Tutorial) was pulled out of its original "Concepts &
// Architecture" category into its own pinned-first card instead; that card also
// links out to the Applications Developer Foundations Course, an Academy course
// (lib/sample-data.ts), not a crawled doc — added directly in the page, not here.
import { dateForId, salesCategoryFor, type ResourceItem } from "./developer-data";

const KNOWLEDGE_BASE_DOCS_RAW: Omit<ResourceItem, "date">[] = [
  {
    id: "get-started-quickstart-tutorial",
    title: "Quickstart Tutorial",
    description: "Quick-start guide for building a temperature alert application using Vantiq's AI capabilities and Claude Code.",
    type: "Tutorial",
    category: "Get Started",
    href: "https://dev.vantiq.com/docs/system/tutorials/quickstart/",
  },
  {
    id: "client-development-client-builder",
    title: "Client Builder",
    description: "Tutorial for creating an invoice application using Vantiq's Client Builder with forms, tables, and gauges.",
    type: "Tutorial",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/client/",
  },
  {
    id: "client-development-client-builder-reference-guide",
    title: "Client Builder Reference Guide",
    description: "Complete reference guide for Client Builder API classes, functions, properties, and event handlers for Vantiq client development.",
    type: "Reference",
    category: "Client Development",
    href: "https://test.vantiq.com/docs/system/cbref/",
  },
  {
    id: "client-development-client-builder-user-s-guide",
    title: "Client Builder User's Guide",
    description: "User's guide for building interactive clients using Vantiq's Client Builder with models, views, and controllers.",
    type: "Reference",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/cbuser/",
  },
  {
    id: "client-development-client-components",
    title: "Client Components",
    description: "Tutorial demonstrating how to author and consume reusable Client Components in Vantiq applications.",
    type: "Tutorial",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/clientcomponenttutorial/",
  },
  {
    id: "client-development-client-components-user-s-guide",
    title: "Client Components User's Guide",
    description: "User guide for creating, editing, and consuming custom client components in the Vantiq platform.",
    type: "Reference",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/ccug/",
  },
  {
    id: "client-development-client-styling-user-s-guide",
    title: "Client Styling User's Guide",
    description: "Guide to styling Vantiq Clients using themes, widget properties, CSS, and navigation bar customization.",
    type: "Reference",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/cbstyling/",
  },
  {
    id: "client-development-client-to-component-conversaion",
    title: "Client to Component Conversaion",
    description: "Guide for converting Vantiq Clients into reusable Components with code examples and best practices.",
    type: "Article",
    category: "Client Development",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks/",
  },
  {
    id: "client-development-dynamic-client-content",
    title: "Dynamic Client Content",
    description: "Guide demonstrating four methods to dynamically show/hide widgets in Vantiq Client applications at runtime.",
    type: "Article",
    category: "Client Development",
    href: "https://community.vantiq.com/forums/topic/new-developer-tiqs-tricks/",
  },
  {
    id: "client-development-dynamic-map-view-widget",
    title: "Dynamic Map View Widget",
    description: "Tutorial demonstrating how to use Vantiq's DynamicMapView widget with Google Maps API integration for real-time location tracking.",
    type: "Article",
    category: "Client Development",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-the-dynamicmapview-widget/",
  },
  {
    id: "client-development-floor-plan",
    title: "Floor Plan",
    description: "Tutorial for building floor plan clients in Vantiq using simulated resident location data and GeoJSON objects for tracking.",
    type: "Tutorial",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/imagemaptutorial/",
  },
  {
    id: "client-development-how-to-video-shorts-client-css",
    title: "How To Video Shorts: Client CSS",
    description: "Short video demonstrating how developers can upload CSS files to customize Vantiq Client widget appearance.",
    type: "Video",
    category: "Client Development",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-client-css/",
  },
  {
    id: "client-development-how-to-video-shorts-client-layouts",
    title: "How To Video Shorts: Client Layouts",
    description: "Layout widgets in Vantiq Client Builder enable responsive design across devices by organizing content without reordering.",
    type: "Video",
    category: "Client Development",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-client-layouts/",
  },
  {
    id: "client-development-layout-management-user-s-guide",
    title: "Layout Management User's Guide",
    description: "Guide to layout management in Vantiq Clients, covering containers, widgets, sizing, and responsive design principles.",
    type: "Reference",
    category: "Client Development",
    href: "https://dev.vantiq.com/docs/system/layout/",
  },
  {
    id: "client-development-public-clients",
    title: "Public Clients",
    description: "Public Clients enable Vantiq users without platform credentials to access applications through designated public resources.",
    type: "Article",
    category: "Client Development",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-public-clients/",
  },
  {
    id: "developer-guides-client-builder-development-standards",
    title: "VANTIQ Developers Guide Series \u2013 Client Builder Development Standards",
    description: "Document providing Vantiq's recommended development standards for optimal Client Builder project development.",
    type: "Guide",
    category: "Developer Guides",
    href: "https://community.vantiq.com/docs/vantiq-developers-guide-client-builder-development-standard/",
  },
  {
    id: "concepts-architecture-build-your-own-tools",
    title: "Build Your Own Tools",
    description: "Tutorial on creating reusable Conversation Display and Management tools for a Vantiq pump repair system with AI.",
    type: "Article",
    category: "Concepts & Architecture",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-and-tricks-building-your-own-tools/",
  },
  {
    id: "concepts-architecture-domain-and-multi-domain-integration-with-vantiq",
    title: "Domain and Multi-Domain Integration with Vantiq",
    description: "Vantiq platform addresses domain and multi-domain integration challenges through event-driven architecture and distributed processing capabilities.",
    type: "Guide",
    category: "Concepts & Architecture",
    href: "https://community.vantiq.com/docs/42956/",
  },
  {
    id: "concepts-architecture-event-driven-integration",
    title: "Event Driven Integration",
    description: "Event-driven integration approaches for system communication using events, producers, consumers, and brokers for real-time responsiveness.",
    type: "Guide",
    category: "Concepts & Architecture",
    href: "https://community.vantiq.com/docs/vantiq-event-driven-integration/",
  },
  {
    id: "concepts-architecture-event-driven-thinking",
    title: "Event Driven Thinking",
    description: "Event-driven thinking transforms enterprise systems to process real-time business events asynchronously through loosely coupled services.",
    type: "Guide",
    category: "Concepts & Architecture",
    href: "https://community.vantiq.com/docs/event-driven-thinking/",
  },
  {
    id: "developer-guides-introduction-to-intelligence-in-vantiq-applications",
    title: "VANTIQ Developers Guide - Introduction to Intelligence in VANTIQ Applications",
    description: "Guide explaining four complementary forms of intelligence for real-time systems: rules, predictive AI, generative AI, and agentic AI.",
    type: "Guide",
    category: "Developer Guides",
    href: "https://community.vantiq.com/docs/vantiq-developers-guide-introduction-to-intelligence-in-vantiq-applications/",
  },
  {
    id: "developer-guides-designing-vantiq-applications",
    title: "VANTIQ Developers Guide Series - Designing VANTIQ Applications",
    description: "Guide covering the design phase of building real-time, event-driven Vantiq applications across requirements, architecture, services, and AI agents.",
    type: "Guide",
    category: "Developer Guides",
    href: "https://community.vantiq.com/docs/vantiq-developers-guide-designing-vantiq-applications/",
  },
  {
    id: "developer-guides-introduction-to-vantiq-development",
    title: "VANTIQ Developers Guide Series - Introduction to VANTIQ Development",
    description: "36-page conceptual guide introducing developers to Vantiq's real-time, event-driven application platform and development methodology.",
    type: "Guide",
    category: "Developer Guides",
    href: "https://community.vantiq.com/docs/vantiq-developers-guide-introduction-to-vantiq-development/",
  },
  {
    id: "developer-guides-server-development-standards",
    title: "VANTIQ Developers Guide Series \u2013 Server Development Standards",
    description: "Guide documenting Vantiq's recommended standards for optimal Service Builder server development projects.",
    type: "Guide",
    category: "Developer Guides",
    href: "https://community.vantiq.com/docs/vantiq-developers-guide-series-server-development-standards/",
  },
  {
    id: "collaboration-advanced-collaborations",
    title: "Advanced Collaborations",
    description: "Advanced tutorial on building collaborative applications using recommendation, notification loops, tracking, and responder assignment patterns.",
    type: "Tutorial",
    category: "Collaboration",
    href: "https://dev.vantiq.com/docs/system/tutorials/advancedcollaborations/",
  },
  {
    id: "ai-genai-collaborations-agents",
    title: "Agents",
    description: "Guide for building GenAI agents in the Vantiq platform combining application logic with large language models.",
    type: "Reference",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/agents/",
  },
  {
    id: "ai-genai-collaborations-conversation",
    title: "Conversation",
    description: "Tutorial for building a chat-like generative AI Client application using Vantiq's Conversation Widget integrated with LLMs.",
    type: "Tutorial",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/tutorials/conversationtutorial/",
  },
  {
    id: "ai-genai-collaborations-create-a-mcp-server-in-a-vantiq-project",
    title: "Create a MCP Server in a Vantiq Project",
    description: "",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/forums/topic/developer-how-to\u2026ervers-in-vantiq/",
  },
  {
    id: "ai-genai-collaborations-genai-builder-guide",
    title: "GenAI Builder Guide",
    description: "GenAI Builder enables developers to create complex generative AI flows using LLMs, semantic indexes, and various components.",
    type: "Reference",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/genaibuilder/",
  },
  {
    id: "ai-genai-collaborations-genai-builder-tools",
    title: "GenAI Builder Tools",
    description: "Developers can use the GenAI Builder to create complex generative AI functionality through visual procedural flows.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/forums/topic/41540/",
  },
  {
    id: "ai-genai-collaborations-genai-builder-tutorial",
    title: "GenAI Builder Tutorial",
    description: "Tutorial covering GenAI Builder components for creating custom flows including RAG, conversations, streaming, content ingestion, and guardrails.",
    type: "Tutorial",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/tutorials/genaibuilder/",
  },
  {
    id: "ai-genai-collaborations-generative-ai-functions-tools",
    title: "Generative AI Functions (Tools)",
    description: "Tutorial on using Generative AI Functions in Vantiq to enable LLMs to answer real-time application questions.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-generative-ai-functions/",
  },
  {
    id: "collaboration-generative-ai-with-collaborations",
    title: "Generative AI with Collaborations",
    description: "How to use Vantiq Collaborations to build AI-assisted applications with continuous context awareness and conversation memory.",
    type: "Article",
    category: "Collaboration",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-generative-ai-with-collaborations/",
  },
  {
    id: "ai-genai-collaborations-how-to-video-shorts-llm-playground",
    title: "How To Video Shorts - LLM Playground",
    description: "Video tutorial demonstrating how to use the LLM Playground feature within the Vantiq platform.",
    type: "Video",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-llm-playground/",
  },
  {
    id: "ai-genai-collaborations-how-to-video-shorts-ai-tools-functions",
    title: "How To Video Shorts: AI Tools (Functions)",
    description: "AI Functions enable generative AI to call procedures for real-time data access and external system queries.",
    type: "Video",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-ai-functions/",
  },
  {
    id: "ai-genai-collaborations-how-to-video-shorts-multi-modal-example",
    title: "How To Video Shorts: Multi-Modal Example",
    description: "Video tutorial demonstrating multi-modal capabilities using an LLM for image description in Vantiq.",
    type: "Video",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-multi-modal-example/",
  },
  {
    id: "ai-genai-collaborations-how-to-video-shorts-using-generative-ai-in-applications",
    title: "How To Video Shorts: Using Generative AI in Applications",
    description: "Video tutorial demonstrating how to integrate generative AI capabilities into Vantiq applications for automated responses.",
    type: "Video",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-using-generative-ai-in-applications/",
  },
  {
    id: "collaboration-how-to-videos-maintaining-ai-conversations-in-collaborations",
    title: "How To Videos - Maintaining AI Conversations in Collaborations",
    description: "How-to video demonstrating maintaining AI conversations within Vantiq collaborations.",
    type: "Video",
    category: "Collaboration",
    href: "https://community.vantiq.com/docs/how-to-videos-maintaining-ai-conversations-in-collaborations/",
  },
  {
    id: "collaboration-how-to-video-shorts-managing-ai-conversations",
    title: "How-To Video Shorts: Managing AI Conversations",
    description: "How-to video guide demonstrating managing AI conversations in Vantiq using service state and collaborations.",
    type: "Article",
    category: "Collaboration",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-managing-ai-conversations/",
  },
  {
    id: "ai-genai-collaborations-how-to-videos-ai-design-model-assistant",
    title: "How-To Videos: AI Design Model Assistant",
    description: "Video tutorial demonstrating how Vantiq's AI Design Model Assistant generates application frameworks from natural language descriptions.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-videos-ai-design-model-assistant/",
  },
  {
    id: "ai-genai-collaborations-how-to-videos-ai-documentation-search",
    title: "How-To Videos: AI Documentation Search",
    description: "How-To Videos on using AI-powered documentation search to quickly find answers in Vantiq documentation.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/how-to-videos-ai/",
  },
  {
    id: "collaboration-introduction-to-collaboration",
    title: "Introduction to Collaboration",
    description: "Tutorial for building a heart rate monitoring collaboration app with patient notifications and first responder coordination.",
    type: "Tutorial",
    category: "Collaboration",
    href: "https://dev.vantiq.com/docs/system/tutorials/introcollaboration/",
  },
  {
    id: "ai-genai-collaborations-llm-reference-guide",
    title: "LLM Reference Guide",
    description: "Guide for configuring Large Language Models from AWS, Google, Azure, NVIDIA, OpenAI, Anthropic, and HuggingFace with Vantiq integration.",
    type: "Reference",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/llms/",
  },
  {
    id: "ai-genai-collaborations-managing-ai-conversation",
    title: "Managing AI Conversation",
    description: "Managing AI conversation memory programmatically using Vantiq's ChatMessage and ConversationMemory services.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-managing-ai-conversation-memory-w-service-procedure/",
  },
  {
    id: "ai-genai-collaborations-open-inference",
    title: "Open Inference",
    description: "Tutorial demonstrating how to use Open Inference Protocol with Vantiq Remote sources to invoke AI models on Triton Inference Server.",
    type: "Tutorial",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/tutorials/openinference/",
  },
  {
    id: "ai-genai-collaborations-open-inference-guide",
    title: "Open Inference Guide",
    description: "Guide to using the Open Inference Protocol with Vantiq Remote sources for AI model communication.",
    type: "Reference",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/openinference/",
  },
  {
    id: "ai-genai-collaborations-semantic-search-guide",
    title: "Semantic Search Guide",
    description: "Guide to implementing semantic search and retrieval augmented generation using embeddings and vector databases in Vantiq.",
    type: "Reference",
    category: "AI & GenAI",
    href: "https://dev.vantiq.com/docs/system/semanticsearch/",
  },
  {
    id: "ai-genai-collaborations-streaming-ai-output",
    title: "Streaming AI Output",
    description: "Developer guide on implementing streaming AI output in Vantiq using GenAI procedures and multiple execution methods.",
    type: "Article",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-streaming-ai-output/",
  },
  {
    id: "ai-genai-collaborations-supporting-semantic-search",
    title: "Supporting Semantic Search",
    description: "Semantic search enables querying data by contextual meaning using embeddings, vector databases, and generative AI for conversational 'Chat Your Data' capabilities.",
    type: "Guide",
    category: "AI & GenAI",
    href: "https://community.vantiq.com/docs/43770/",
  },
  {
    id: "core-platform-api-reference-guide",
    title: "API Reference Guide",
    description: "Comprehensive guide to Vantiq API operations, bindings, authentication, and resource management across HTTP, WebSockets, and VAIL.",
    type: "Reference",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/api/",
  },
  {
    id: "core-platform-cache-services",
    title: "Cache Services",
    description: "Guide on using Vantiq Cache Services to minimize database interactions and improve application performance.",
    type: "Article",
    category: "Core Platform",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-cache-services/",
  },
  {
    id: "core-platform-debugging",
    title: "Debugging",
    description: "Tutorial demonstrating how to use the Autopsy Debugger tool to trace, debug, and test Vantiq rules.",
    type: "Tutorial",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/tutorials/debugtutorial/",
  },
  {
    id: "core-platform-filters",
    title: "Filters",
    description: "Developer guide explaining four filter activity patterns in Vantiq for event processing and real-time responsiveness.",
    type: "Article",
    category: "Core Platform",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-filters-for-fun-profit/",
  },
  {
    id: "core-platform-how-to-video-the-join-activity-pattern",
    title: "How To Video - The Join Activity Pattern",
    description: "Two-minute video explaining how to configure the Join task in Visual Event Handlers for correlating event streams.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/how-to-video-the-join-activity-pattern/",
  },
  {
    id: "core-platform-how-to-video-shorts-calling-procedures-by-properties",
    title: "How To Video Shorts: Calling Procedures by Properties",
    description: "Video tutorial demonstrating how to call procedures by their properties in the VAIL language.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-calling-procedures-by-properties/",
  },
  {
    id: "core-platform-how-to-video-shorts-splitbygroup",
    title: "How To Video Shorts: SplitByGroup",
    description: "This video demonstrates how to use the SplitByGroup Activity Pattern for processing event subsets in Services.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-splitbygroup/",
  },
  {
    id: "core-platform-how-to-video-shorts-the-vantiq-api",
    title: "How To Video Shorts: The Vantiq API",
    description: "Video tutorial explaining how to access Vantiq resources externally using HTTPS REST, WSS methods, and JSON structures.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-the-vantiq-api/",
  },
  {
    id: "core-platform-how-to-video-shorts-the-vantiq-ide",
    title: "How To Video Shorts: The Vantiq IDE",
    description: "Overview of the Vantiq IDE as a visual workspace for developers to design, develop, test, and deploy projects.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/the-vantiq-ide/",
  },
  {
    id: "core-platform-how-to-video-shorts-the-vantiq-version-control-system",
    title: "How To Video Shorts: The Vantiq Version Control System",
    description: "Guide to Vantiq's Version Control System for tracking project progress and merging developer work.",
    type: "Video",
    category: "Core Platform",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-the-vantiq-version-control-system/",
  },
  {
    id: "core-platform-ide-user-s-guide",
    title: "IDE User's Guide",
    description: "Comprehensive guide to Vantiq IDE features, navigation, panes, development tools, and deployment capabilities.",
    type: "Reference",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/ide/",
  },
  {
    id: "core-platform-resource-reference-guide",
    title: "Resource Reference Guide",
    description: "Comprehensive reference guide for Vantiq system resources including types, operations, security models, and access rights.",
    type: "Reference",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/resourceguide/",
  },
  {
    id: "core-platform-sharing-resources",
    title: "Sharing Resources",
    description: "Four methods to share Vantiq namespace resources including Components across projects and Namespaces.",
    type: "Article",
    category: "Core Platform",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-sharing-resources/",
  },
  {
    id: "core-platform-storage-managers-reference-guide",
    title: "Storage Managers Reference Guide",
    description: "Storage managers enable pluggable remote data stores into Vantiq namespaces for persistent type operations.",
    type: "Reference",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/storagemanagers/",
  },
  {
    id: "core-platform-transformations",
    title: "Transformations",
    description: "Explores the Transformation Activity Pattern in Vantiq, demonstrating five practical examples for modifying event structures.",
    type: "Article",
    category: "Core Platform",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-transformations/",
  },
  {
    id: "core-platform-vail-reference-guide",
    title: "VAIL Reference Guide",
    description: "Comprehensive reference guide for the VAIL language used to build event-driven applications on the Vantiq platform.",
    type: "Reference",
    category: "Core Platform",
    href: "https://dev.vantiq.com/docs/system/rules/",
  },
  {
    id: "core-platform-web-based-apis",
    title: "Web-Based APIs",
    description: "Guide for integrating Vantiq applications with web-based REST APIs using REMOTE sources and VAIL statements.",
    type: "Article",
    category: "Core Platform",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-integrating-vantiq-with-web-based-apis/",
  },
  {
    id: "assemblies-assemblies",
    title: "Assemblies",
    description: "Tutorial for building, publishing, and consuming reusable, configurable Assemblies in Vantiq applications.",
    type: "Tutorial",
    category: "Assemblies",
    href: "https://dev.vantiq.com/docs/system/tutorials/assemblytutorial/",
  },
  {
    id: "assemblies-assemblies-reference-guide",
    title: "Assemblies Reference Guide",
    description: "Comprehensive guide to creating, authoring, and consuming reusable Vantiq Assemblies with configurable components.",
    type: "Reference",
    category: "Assemblies",
    href: "https://dev.vantiq.com/docs/system/assemblies/",
  },
  {
    id: "assemblies-camel-assemblies",
    title: "Camel Assemblies",
    description: "Vantiq introduces Camel Assemblies, pre-built integration modules in a public catalog for connecting to external systems.",
    type: "Article",
    category: "Assemblies",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-and-tricks-camel-assemblies-for-integration/",
  },
  {
    id: "operations-deployment-admin-administrators-reference-guide",
    title: "Administrators Reference Guide",
    description: "Guide for Vantiq administrators covering user authorization, namespace creation, and system administration tasks.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/namespaces/",
  },
  {
    id: "operations-deployment-admin-cli-reference-guide",
    title: "CLI Reference Guide",
    description: "Comprehensive guide to Vantiq CLI commands, installation, profiles, and operations for managing development resources.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/cli/",
  },
  {
    id: "operations-deployment-admin-deployment",
    title: "Deployment",
    description: "Tutorial for deploying Vantiq applications to multi-node environments with distributed resource partitioning.",
    type: "Tutorial",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/tutorials/deploymenttutorial/",
  },
  {
    id: "operations-deployment-admin-deployment-reference-guide",
    title: "Deployment Reference Guide",
    description: "Guide for configuring Vantiq server networks, deploying resources, and bootstrapping distributed nodes.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/config/",
  },
  {
    id: "operations-deployment-admin-deployment-tool-user-s-guide",
    title: "Deployment Tool User's Guide",
    description: "Guide for deploying Vantiq projects using the Deployment Tool with nodes, environments, and partitions.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/deploymentuser/",
  },
  {
    id: "operations-deployment-admin-diagnosing-faults-and-scalability-issues-in-vantiq-applications",
    title: "Diagnosing Faults and Scalability Issues In Vantiq Applications",
    description: "Diagnostic strategies for identifying faults and scalability issues in Vantiq event-driven applications through systematic testing and modeling.",
    type: "Article",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/docs/diagnosing-faults-and-scalability-issues-in-vantiq-applications-2/",
  },
  {
    id: "operations-deployment-admin-discovering-current-session-information",
    title: "Discovering Current Session Information",
    description: "Guide to discovering current session and user information in Vantiq IDE, Context Service, and Client procedures.",
    type: "Article",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-discovering-current-session-information/",
  },
  {
    id: "operations-deployment-admin-external-lifecycle-management-guide",
    title: "External Lifecycle Management Guide",
    description: "Guide for managing external Kubernetes clusters with Vantiq namespaces, including K8s Worker deployment and installation management.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/extlifecycle/",
  },
  {
    id: "operations-deployment-admin-how-to-video-shorts-invite-other-users-to-your-namespace",
    title: "How To Video Shorts: Invite Other Users to Your Namespace",
    description: "Video tutorial demonstrating how to invite other Vantiq users to access your Namespace.",
    type: "Video",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-invite-other-users-to-your-namespace/",
  },
  {
    id: "operations-deployment-admin-how-to-videos-secrets",
    title: "How To Videos: Secrets",
    description: "Video tutorial explaining how to create, store, and reference sensitive information using Vantiq Secrets securely.",
    type: "Video",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/docs/how-to-videos-secrets/",
  },
  {
    id: "operations-deployment-admin-monitoring-with-grafana",
    title: "Monitoring with Grafana",
    description: "Guide to using Grafana dashboards for monitoring Vantiq namespace resources and server performance metrics.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/grafana/",
  },
  {
    id: "operations-deployment-admin-production-applications-best-practices",
    title: "Production Applications Best Practices",
    description: "Best practices for transitioning operational applications to production-ready status in Vantiq platform environments.",
    type: "Article",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/docs/production-applications-best-practices/",
  },
  {
    id: "operations-deployment-admin-reliable-messaging-guide",
    title: "Reliable Messaging Guide",
    description: "Guides configuring at-least-once reliable messaging delivery for Vantiq events across topics, services, and sources.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/reliability/",
  },
  {
    id: "operations-deployment-admin-security-secrets",
    title: "Security Secrets",
    description: "Guide to using Vantiq Secrets to secure sensitive information like API keys in shared namespaces.",
    type: "Article",
    category: "Operations, Deployment & Admin",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-security-secrets/",
  },
  {
    id: "operations-deployment-admin-user-and-namespace-administration",
    title: "User and Namespace Administration",
    description: "Tutorial demonstrates how to administer Vantiq users and namespaces, including creating users and managing access permissions.",
    type: "Tutorial",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/tutorials/admin/",
  },
  {
    id: "operations-deployment-admin-vantiq-edge-reference-guide",
    title: "Vantiq Edge Reference Guide",
    description: "Guide for deploying and managing Vantiq Edge non-clustered servers in edge computing environments.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/vantiqedge/",
  },
  {
    id: "operations-deployment-admin-workload-management",
    title: "Workload Management",
    description: "Workload management system controlling resource usage per Organization through quotas, rate limiting, and credit-based work management.",
    type: "Reference",
    category: "Operations, Deployment & Admin",
    href: "https://dev.vantiq.com/docs/system/workloadmanagement/",
  },
  {
    id: "external-sources-integrations-amqp-reference-guide",
    title: "AMQP Reference Guide",
    description: "AMQP 1.0 source integration guide covering configuration, SSL setup, and Azure service examples.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/amqp/",
  },
  {
    id: "external-sources-integrations-chatbot-reference-guide",
    title: "CHATBOT Reference Guide",
    description: "Guide for integrating Microsoft Azure Bot Services chatbots with Vantiq to relay messages from chat platforms.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/chatbot/",
  },
  {
    id: "external-sources-integrations-email-reference-guide",
    title: "Email Reference Guide",
    description: "Configure and use EMAIL sources to send notifications through SMTP servers in Vantiq applications.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/email/",
  },
  {
    id: "external-sources-integrations-enterprise-connectors-reference-guide",
    title: "Enterprise Connectors Reference Guide",
    description: "Enterprise Connectors enable Vantiq to communicate with external systems through extensible source types.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/entcon/",
  },
  {
    id: "external-sources-integrations-external-sources-reference-guide",
    title: "External Sources Reference Guide",
    description: "Guide to integrating external data sources into Vantiq for streaming, querying, and publishing operations.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/source/",
  },
  {
    id: "external-sources-integrations-google-cloud-pub-sub-reference-guide",
    title: "Google Cloud Pub/Sub Reference Guide",
    description: "Google Cloud Pub/Sub source integration for Vantiq enables publishing to topics and consuming from subscriptions.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/gcps/",
  },
  {
    id: "external-sources-integrations-how-to-video-shorts-how-to-create-a-built-in-source",
    title: "How To Video Shorts: How to Create a Built-In Source",
    description: "Video guide demonstrating step-by-step process for creating built-in sources in Vantiq to integrate message protocols and APIs.",
    type: "Video",
    category: "External Sources & Integrations",
    href: "https://community.vantiq.com/docs/how-to-create-a-built-in-source/",
  },
  {
    id: "external-sources-integrations-image-processing-guide",
    title: "Image Processing Guide",
    description: "Vantiq image processing capabilities for acquiring, manipulating, and analyzing images using neural networks and TensorFlow models.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/imageprocessing/",
  },
  {
    id: "external-sources-integrations-kafka-reference-guide",
    title: "KAFKA Reference Guide",
    description: "Kafka source integration guide covering creation, message production/consumption, configuration, and SSL setup.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/kafka/",
  },
  {
    id: "external-sources-integrations-mqtt-reference-guide",
    title: "MQTT Reference Guide",
    description: "Configure MQTT sources in Vantiq to read streaming data, publish notifications, and set up SSL security.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/mqtt/",
  },
  {
    id: "external-sources-integrations-push-notification-reference-guide",
    title: "Push Notification Reference Guide",
    description: "Guide for integrating PUSH_NOTIF sources to send Apple and Android push notifications to mobile apps.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/pushnotify/",
  },
  {
    id: "external-sources-integrations-remote-reference-guide",
    title: "Remote Reference Guide",
    description: "Guide for configuring and using Remote sources to integrate HTTP/REST services with Vantiq applications.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/remote/",
  },
  {
    id: "external-sources-integrations-sms-reference-guide",
    title: "SMS Reference Guide",
    description: "Guide for integrating Twilio SMS services to send text messages through Vantiq sources.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/sms/",
  },
  {
    id: "external-sources-integrations-sources",
    title: "Sources",
    description: "Tutorial for creating weather data sources, processing external data, and using rules to store and manipulate source events.",
    type: "Tutorial",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/tutorials/sourcetutorial/",
  },
  {
    id: "external-sources-integrations-using-the-video-sources",
    title: "Using the Video Sources",
    description: "Tutorial on using Vantiq's new Video Source to capture images from cameras and analyze them with AI.",
    type: "Article",
    category: "External Sources & Integrations",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-using-the-video-source/",
  },
  {
    id: "external-sources-integrations-video-reference-guide",
    title: "Video Reference Guide",
    description: "VIDEO source integration guide covering image data retrieval from cameras and files with streaming and query capabilities.",
    type: "Reference",
    category: "External Sources & Integrations",
    href: "https://dev.vantiq.com/docs/system/sources/video/",
  },
  {
    id: "service-development-app-components",
    title: "App Components",
    description: "Tutorial for creating reusable App Components in Vantiq by extracting duplicated tasks from event handlers.",
    type: "Tutorial",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/componenttutorial/",
  },
  {
    id: "service-development-app-components-reference-guide",
    title: "App Components Reference Guide",
    description: "App Components allow developers to build reusable, configurable activity pattern fragments for sharing in applications.",
    type: "Reference",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/appcomponents/",
  },
  {
    id: "service-development-service-builder-reference-guide",
    title: "Service Builder Reference Guide",
    description: "Guide to building Vantiq services with interface, implementation, and testing through the service builder.",
    type: "Reference",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/services/",
  },
  {
    id: "service-development-service-event-handlers",
    title: "Service Event Handlers",
    description: "Guide explaining Service Event Handlers in Vantiq, covering Interface and Implement Tab event categorization and types.",
    type: "Article",
    category: "Service Development",
    href: "https://community.vantiq.com/forums/topic/developer-tiqs-tricks-service-event-handlers/",
  },
  {
    id: "service-development-service-state-management",
    title: "Service State Management",
    description: "Vantiq platform facilities for managing service state, including stateless services, stateful services with global and partitioned state, and collaborations.",
    type: "Reference",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/servicestatemgmt/",
  },
  {
    id: "service-development-stateful-services",
    title: "Stateful Services",
    description: "Tutorial teaching how to use stateful services to store engine sensor data efficiently in memory and database.",
    type: "Tutorial",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/statefulservices/",
  },
  {
    id: "service-development-visual-event-handler-reference-guide",
    title: "Visual Event Handler Reference Guide",
    description: "Comprehensive reference guide for Visual Event Handlers (Apps) in Vantiq, covering activity patterns, configuration, and event processing capabilities.",
    type: "Reference",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/apps/",
  },
  {
    id: "catalog-catalog-api-guide",
    title: "Catalog API Guide",
    description: "Guide to Vantiq Catalog API operations, procedures, and integration methods for external applications.",
    type: "Reference",
    category: "Catalog",
    href: "https://dev.vantiq.com/docs/system/brokerapi/",
  },
  {
    id: "catalog-catalog-reference-guide",
    title: "Catalog Reference Guide",
    description: "The Vantiq Catalog connects namespaces to publish and subscribe to events, services, assemblies, and semantic indexes across distributed applications.",
    type: "Reference",
    category: "Catalog",
    href: "https://dev.vantiq.com/docs/system/broker/",
  },
  {
    id: "catalog-catalog-security-guide",
    title: "Catalog Security Guide",
    description: "Guide explaining security mechanisms for controlling publisher and subscriber access to Vantiq Catalog event types.",
    type: "Reference",
    category: "Catalog",
    href: "https://dev.vantiq.com/docs/system/brokersecurity/",
  },
  {
    id: "catalog-catalogs",
    title: "Catalogs",
    description: "Tutorial for using the Vantiq Catalog to publish and subscribe to events across multiple namespaces.",
    type: "Tutorial",
    category: "Catalog",
    href: "https://dev.vantiq.com/docs/system/tutorials/eventbroker/",
  },
  {
    id: "design-modeler-design-modeler-reference-guide",
    title: "Design Modeler Reference Guide",
    description: "Visual IDE tool for building Vantiq systems by connecting Services and Clients graphically.",
    type: "Reference",
    category: "Design Modeler",
    href: "https://dev.vantiq.com/docs/system/designmodeler/",
  },
  {
    id: "design-modeler-system-modeler",
    title: "System Modeler",
    description: "Tutorial introducing developers to Vantiq's System Modeler for low-code event-driven business process modeling.",
    type: "Tutorial",
    category: "Design Modeler",
    href: "https://dev.vantiq.com/docs/system/tutorials/systemmod/",
  },
  {
    id: "tutorials-analytics",
    title: "Analytics",
    description: "Tutorial for integrating Microsoft Azure Machine Learning Studio sentiment analysis with Vantiq using Analytics Sources.",
    type: "Tutorial",
    category: "Service Development",
    href: "https://dev.vantiq.com/docs/system/tutorials/analytics/",
  },
  {
    id: "analytics-how-to-video-shorts-analytics-and-computestatistics",
    title: "How To Video Shorts: Analytics and ComputeStatistics",
    description: "Video tutorial explaining ComputeStatistics and Analytics activity patterns for event processing in Vantiq Services.",
    type: "Video",
    category: "Service Development",
    href: "https://community.vantiq.com/docs/how-to-video-shorts-analytics-and-computestatistics/",
  },
  {
    id: "testing-captures",
    title: "Captures",
    description: "Guide for recording, managing, and exporting application events using Vantiq's Capture testing tool for verification and testing.",
    type: "Reference",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/capture/",
  },
  {
    id: "testing-event-generators",
    title: "Event Generators",
    description: "Event Generators simulate real-world data into Vantiq systems for testing, development, and performance validation.",
    type: "Reference",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/eventgenerators/",
  },
  {
    id: "testing-testing-reference-guide",
    title: "Testing Reference Guide",
    description: "Vantiq Testing Reference Guide covering unit tests, integration tests, test definitions, and test execution methods.",
    type: "Reference",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/tests/",
  },
  {
    id: "testing-testing-the-debugging-tutorial",
    title: "Testing the Debugging Tutorial",
    description: "Tutorial on testing rules through unit tests, setup/cleanup procedures, and test suites in Vantiq.",
    type: "Tutorial",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/tutorials/testdebugtutorial/",
  },
  {
    id: "testing-testing-the-introductory-tutorial",
    title: "Testing the Introductory Tutorial",
    description: "Tutorial for creating and running integration tests for the EngineMonitor Service in Vantiq.",
    type: "Tutorial",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/tutorials/testIntroTutorial/",
  },
  {
    id: "testing-testing-the-source-tutorial",
    title: "Testing the Source Tutorial",
    description: "Tutorial on creating unit tests for Vantiq Source Rules and Procedures with mocking capabilities.",
    type: "Tutorial",
    category: "Testing",
    href: "https://dev.vantiq.com/docs/system/tutorials/testsourcetutorial/",
  },
  {
    id: "branding-white-labeling-android-mobile-app",
    title: "Android Mobile App",
    description: "Guide for customizing and branding the Vantiq Android mobile app for Google Play Store deployment.",
    type: "Reference",
    category: "Branding & White-Labeling",
    href: "https://dev.vantiq.com/docs/system/androidbranding/",
  },
  {
    id: "branding-white-labeling-react-native-app",
    title: "React Native App",
    description: "Vantiq React Native module provides APIs for authentication, database operations, procedures, and push notifications.",
    type: "Reference",
    category: "Branding & White-Labeling",
    href: "https://dev.vantiq.com/docs/system/react/",
  },
  {
    id: "branding-white-labeling-white-labeling-vantiq",
    title: "White-Labeling Vantiq",
    description: "Guide to customizing Vantiq IDE branding through webUIConfig.json configuration for private cloud deployments.",
    type: "Reference",
    category: "Branding & White-Labeling",
    href: "https://dev.vantiq.com/docs/system/idebranding/",
  },
  {
    id: "branding-white-labeling-ios-mobile-app",
    title: "iOS Mobile App",
    description: "Guide for customizing and rebranding the Vantiq iOS mobile app for Apple App Store submission.",
    type: "Reference",
    category: "Branding & White-Labeling",
    href: "https://dev.vantiq.com/docs/system/iosbranding/",
  },
];

// dateForId is a placeholder — see the comment on it in developer-data.ts.
// This corpus has real crawled titles/descriptions/hrefs (see file header)
// but no crawled publish date, so sorting by date uses the same synthetic
// scheme as the rest of the resource catalog.
export const KNOWLEDGE_BASE_DOCS: ResourceItem[] = KNOWLEDGE_BASE_DOCS_RAW.map((doc) => ({
  ...doc,
  date: dateForId(doc.id),
  salesCategory: salesCategoryFor(doc.type, doc.category),
}));
